# PhantomSMP by Simon Chuu

# For help, follow the plugin project link below:
# https://github.com/SimonOrJ/PhantomSMP/

# Remove phantoms that try to target player slept within three (Minecraft)
# days?
#   true = remove phantom targeting rested player
#   false = Keep phantoms (and make phantoms ignore the player)
remove-targeting-rested: true

# Remove phantoms right away when the player sleeps in bed?
#   true = remove phantoms as soon as player sleeps
#   false = Keep phantoms (and let the above option take care of it)
remove-when-sleeping: false

# How many ticks since player rested should phantoms ignore the player?
#   NOTE: Any value under 72000 (3 full Minecraft days) will essentially be
#   ignored for phantom spawning.  It will only have an effect on already
#   spawned phantoms only.
disallow-targeting-for: 72000

# Enable metrics for this plugin? (If unsure, leave it as true)
#   Link to metrics: https://bstats.org/plugin/bukkit/PhantomSMP/
enable-metrics: true
